# Robots schema

# --- !Ups
CREATE TABLE "ROBOT_PARTS" (
    SERIAL VARCHAR(50) PRIMARY KEY,
    NAME VARCHAR(255) NOT NULL,
    NUMBER VARCHAR(255) NOT NULL,
    MANUFACTURER VARCHAR(255) NOT NULL,
    WEIGHT VARCHAR(255) NOT NULL
)

# --- !Downs
DROP TABLE "ROBOT_PARTS"